Repository atlp-rwanda/e-comm-team-techsmith-fn, pull requests merged in 2023-07, with the labels that each got.

#80 #185528222 Develop Sticky Navigation Bar
  src/__tests__/wishlist.test.jsx
  src/styles/navbar.scss
Labels: ready

#82 #185528211 Redesign of the seller dashboard
  package-lock.json
  src/__tests__/chatbox.test.jsx
  src/containers/SellerProductsContainer.jsx
  src/styles/sellerProduct.scss
  vite.config.js
Labels: Done

#78 #185548712 Add DM features to chatroom
  package-lock.json
  src/App.jsx
  src/__tests__/chatbox.test.jsx
  src/__tests__/joinchat.test.jsx
  src/__tests__/participants.test.jsx
  src/components/Chatroom/AddConversation.jsx
  src/components/Chatroom/ChatBox.jsx
  src/components/Chatroom/JoinChat.jsx
  src/components/Chatroom/Message.jsx
  src/components/Chatroom/Participants.jsx
  src/components/Chatroom/Rooms.jsx
  src/components/Navbar.jsx
  src/components/Pagination.jsx
  src/states/api/apiSlice.js
  src/states/features/chat/chatSlice.js
  src/styles/navbar.scss
  src/utils/Arrays.js
  src/utils/Downloads.js
  src/utils/Pagination.js
Labels: work-in-progress

#81 #185528209: calculate and display ratings
  src/components/ProductCard.jsx
  src/components/ProductDetails.jsx
  src/components/Rating.jsx
  src/containers/HomeBrowseCategory.jsx
  src/containers/HomePopularProducts.jsx
  src/containers/ViewAllProductsContainer.jsx
Labels: Done

#83 Conditional Clear Cart
  src/components/Cart.jsx
Labels: Done

#84 #185528222 Develop Sticky Navigation Bar
  src/components/Navbar.jsx
  src/styles/navbar.scss
Labels: ready

#85 #185548712 Bug fix Chatroom DM
  src/components/Chatroom/ChatBox.jsx
  src/components/Pagination.jsx
  src/socket.jsx
  src/states/api/apiSlice.js
Labels: ready

#86 #185548712 Bug fix for the final demo (Chatroom)
  src/components/Chatroom/ChatBox.jsx
  src/components/Chatroom/CreateGroup.jsx
  src/components/Chatroom/CreateUser.jsx
  src/components/Chatroom/Message.jsx
  src/components/Chatroom/Rooms.jsx
  src/components/ProductCard.jsx
  src/components/ProductDetails.jsx
  src/containers/HomePopularProducts.jsx
  src/containers/ProductReviewContainer.jsx
  src/containers/ProductReviewForm.jsx
  src/containers/SearchContainer.jsx
  src/containers/ViewAllProductsContainer.jsx
  src/socket.jsx
  src/states/api/apiSlice.js
  src/states/features/categories/categorySlice.js
  src/states/features/chat/chatSlice.js
  src/styles/navbar.scss
  src/utils/Arrays.js
Labels: ready

#77 #185528206 Integrate WebSockets for Automatic Stock Updates
  .babelrc
  .env.example
  .eslintrc.cjs
  package.json
  src/__tests__/CartSubTotal.test.jsx
  src/__tests__/SingleItemInCart.test.jsx
  src/__tests__/authBlueSide.test.jsx
  src/__tests__/button.test.jsx
  src/__tests__/categories.test.jsx
  src/__tests__/changePassword.test.jsx
  src/__tests__/checkout.test.jsx
  src/__tests__/forgotPassword.test.jsx
  src/__tests__/home.test.jsx
  src/__tests__/loading.test.jsx
  src/__tests__/login.test.jsx
  src/__tests__/profile.test.jsx
  src/__tests__/rolesAndPermissions.test.jsx
  src/__tests__/sellerCollection.test.jsx
  src/__tests__/sellerProduct.test.jsx
  src/__tests__/wishlist.test.jsx
  src/components/AuthBlueSide.jsx
  src/components/Cart.jsx
  src/components/Chatroom/Message.jsx
  src/components/Loading.jsx
  src/components/Navbar.jsx
  src/components/OrderDetails.jsx
  src/components/PaymentContainer.jsx
  src/components/ProductCard.jsx
  src/components/ProductDetails.jsx
  src/components/ShippingDetails.jsx
  src/components/ValidateOrder.jsx
  src/components/changePassword.jsx
  src/constants/API.jsx
  src/constants/index.jsx
  src/containers/BuyerWishlistContainer.jsx
  src/containers/CheckoutContainer.jsx
  src/containers/ContactContainer.jsx
  src/containers/HomeContainer.jsx
  src/containers/HomePopularProducts.jsx
  src/containers/LoginContainer.jsx
  src/containers/MultipleOrdersContainer.jsx
  src/containers/NotFound.jsx
  src/containers/ProfileContainer.jsx
  src/containers/ResetPasswordContainer.jsx
  src/containers/SearchContainer.jsx
  src/containers/SellerProductsContainer.jsx
  src/containers/SignupContainer.jsx
  src/containers/SingleProductContainer.jsx
  src/containers/TopMerchants.jsx
  src/containers/ViewAllProductsContainer.jsx
  src/outlets/SellerRoutes.jsx
  src/pages/index.jsx
  src/socket.jsx
  src/states/api/apiSlice.js
  src/styles/navbar.scss
  src/styles/order.scss
  src/styles/signup.scss
Labels: ready
